# 服务器端口
server:
  port: 8001



# 服务名
spring:
  application:
    name: service-edu
  # nacos服务地址
  #spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


  # 环境设置 : dev、test、prod
  profiles:
    active: dev

# 数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli?serverTimezone=GMT%2B8
    username: root
    password: root

# 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath:com/liuscoding/edu/mapper/xml/*.xml


